Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -230,9 +230,36 @@ jobs:
             echo "STATUS=❌ Build Cancelled!" >> $GITHUB_ENV
           fi
 
+      - name: Check more Information before Notify and Sending
+        id: check-kernel
+        if: success() || failure() || cancelled()
+        run: |
+          if [ "${{ job.status }}" = "success" ]; then
+            echo "BUILD_STATUS=true"
+            if [ -f "${{ env.ANYKERNEL_PATH }}/${{ env.ZIP_NAME }}.zip" ]; then
+              echo "KERNEL_STATUS=true"
+              echo "KERNEL_DOC=${{ env.ANYKERNEL_PATH }}/${{ env.ZIP_NAME }}.zip" >> $GITHUB_ENV
+            elif [ -f "${{ env.KERNEL_PATH }}/${{ env.KERNEL_BOOT_PATH }}/${{ env.IMAGE }}" ]; then
+              echo "KERNEL_STATUS=true"
+              echo "KERNEL_DOC=${{ env.KERNEL_PATH }}/${{ env.KERNEL_BOOT" >> $GITHUB_ENV
+            else
+              echo "KERNEL_STATUS=false"
+              echo "Kernel not found, exiting"
+              exit 1
+            fi
+          fi
+          if [ "${{ job.status }}" = "failure" ] || [ "${{ job.status }}" = "cancelled" ]; then
+            echo "BUILD_STATUS=false"
+            if [ -f "${{ env.KERNEL_PATH }}/build.log" ]; then
+              echo "LOG_STATUS=true" >> $GITHUB_ENV
+            else
+              echo "LOG_STATUS=false" >> $GITHUB_ENV
+            fi
+          fi
+
       - name: Notify to Telegram if Build Successful
         id: notify-if-success
-        if: success() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: github.env.BUILD_STATUS == 'true' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
@@ -248,9 +275,9 @@ jobs:
             Build Type: `${{ env.BUILD_TYPE }}`
             Date: `${{ env.DATE }}`
 
-      - name: Send document to Telegram
+      - name: Send Kernel to Telegram
         id: upload-kernel-and-notify
-        if: success() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != '' && -f $(github.env.ANYKERNEL_PATH }}/github.env.env.ZIP_NAME.zip || github.env.KERNEL_PATH/github.env.KERNEL_BOOT_PATH/github.env.IMAGE)
+        if: github.steps.notify-if-success.conclusion == 'success' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ env.TELEGRAM_TO }}
@@ -264,7 +291,7 @@ jobs:
 
       - name: Notify to Telegram if Build not Successful
         id: notify-if-not-success
-        if: failure() || cancelled() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: github.env.BUILD_STATUS == 'false' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
@@ -282,7 +309,7 @@ jobs:
 
       - name: Send Error log to Telegram
         id: upload-log-and-notify
-        if: failure() || cancelled() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != '' && -f github.env.KERNEL_PATH/build.log
+        if: github.env.LOG_STATUS == 'true' && github.steps.notify-if-not-success.conclusion == 'success' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != '' && -f github.env.KERNEL_PATH/build.log
         uses: appleboy/telegram-action@master
         with:
           to: ${{ env.TELEGRAM_TO }}
