Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,89 +35,84 @@ jobs:
             echo "KERNEL_PATH=kernel"
             echo "ANYKERNEL_PATH=zipper"
             echo "KERNEL_BOOT_PATH=/out/arch/arm64/boot"
+            echo "MSG_URL=https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
+            echo "DOC_URL=https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument"
           } >> $GITHUB_ENV
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
       - name: Clone Toolchains
-        env:
-          CLANG_REPO: ${{ inputs.clang-repo }}
-          GCC64_REPO: ${{ inputs.gcc64-repo }}
-          GCC32_REPO: ${{ inputs.gcc32-repo }}
         run: |
-          if [ -n "$CLANG_REPO" ] && [ "$CLANG_REPO" = "$GCC64_REPO" ] && [ "$CLANG_REPO" = "$GCC32_REPO" ]; then
+          if [ -n "${{ inputs.clang-repo }}" ] && [ "${{ inputs.clang-repo }}" = "${{ inputs.gcc64-repo }}" ] && [ "${{ inputs.clang-repo }}" = "${{ inputs.gcc32-repo }}" ]; then
             echo "Clang, GCC64, and GCC32 URLs are the same, using tools path"
-            TOOLCHAINS_REPO=$CLANG_REPO
+            TOOLCHAINS_REPO=${{ inputs.clang-repo }}
             git clone --depth=1 $TOOLCHAINS_REPO ${{ env.TOOLCHAINS_PATH }}
-          elif [ -n "$CLANG_REPO" ]; then
+          elif [ -n "${{ inputs.clang-repo }}" ]; then
             echo "Clang URL detected"
-            if [[ "$CLANG_REPO" == *.tar.gz ]]; then
+            if [[ "${{ inputs.clang-repo }}" == *.tar.gz ]]; then
             echo "Clang Tarball detected"
               mkdir -p ${{ env.CLANG_PATH }}
-              curl -RLO $CLANG_REPO
+              curl -RLO ${{ inputs.clang-repo }}
               tar -C ${{ env.CLANG_PATH }}/ -xf *.tar.gz
               rm -f *.tar.gz
             else
               echo "Clang Repo detected"
-              git clone --depth=1 $CLANG_REPO ${{ env.CLANG_PATH }}
+              git clone --depth=1 ${{ inputs.clang-repo }} ${{ env.CLANG_PATH }}
             fi
-            if [ -n "$GCC64_REPO" ] && [ -n "$GCC32_REPO" ]; then
+            if [ -n "${{ inputs.gcc64-repo }}" ] && [ -n "${{ inputs.gcc32-repo }}" ]; then
               echo "GCC 64-bit and GCC 32-bit URLs detected"
-              if [ -n "$GCC64_REPO" ] && [ "$GCC64_REPO" = "$GCC32_REPO" ]; then
+              if [ -n "${{ inputs.gcc64-repo }}" ] && [ "${{ inputs.gcc64-repo }}" = "${{ inputs.gcc32-repo }}" ]; then
                 echo "GCC 64-bit and GCC 32-bit URLs are the same, using gcc path"
-                GCC_REPO=$GCC64_REPO
+                GCC_REPO=${{ inputs.gcc64-repo }}
                 git clone --depth=1 $GCC_REPO ${{ env.GCC_PATH }}
               else
-                if [[ "$GCC64_REPO" == *.tar.gz ]]; then
+                if [[ "${{ inputs.gcc64-repo }}" == *.tar.gz ]]; then
                   echo "GCC 64-bit Tarball detected"
                   mkdir -p ${{ env.GCC64_PATH }}
-                  curl -RLO $GCC64_REPO
+                  curl -RLO ${{ inputs.gcc64-repo }}
                   tar -C ${{ env.GCC64_PATH }}/ -xf *.tar.gz
                   rm -f *.tar.gz
                 else
                   echo "GCC 64-bit Repo detected"
-                  git clone --depth=1 $GCC64_REPO ${{ env.GCC64_PATH }}
+                  git clone --depth=1 ${{ inputs.gcc64-repo }} ${{ env.GCC64_PATH }}
                 fi
               fi
-              if [[ "$GCC32_REPO" == *.tar.gz ]]; then
+              if [[ "${{ inputs.gcc32-repo }}" == *.tar.gz ]]; then
                 echo "GCC 32-bit Tarball detected"
                 mkdir -p ${{ env.GCC32_PATH }}
-                curl -RLO $GCC32_REPO
+                curl -RLO ${{ inputs.gcc32-repo }}
                 tar -C ${{ env.GCC32_PATH }}/ -xf *.tar.gz
                 rm -f *.tar.gz
               else
                 echo "GCC 32-bit Repo detected"
-                git clone --depth=1 $GCC32_REPO ${{ env.GCC32_PATH }}
+                git clone --depth=1 ${{ inputs.gcc32-repo }} ${{ env.GCC32_PATH }}
               fi
             fi
-          elif [ -n "$GCC64_REPO" ] && [ -n "$GCC32_REPO" ]; then
+          elif [ -n "${{ inputs.gcc64-repo }}" ] && [ -n "${{ inputs.gcc32-repo }}" ]; then
             echo "GCC 64-bit and GCC 32-bit URLs detected"
-            if [ -n "$GCC64_REPO" ] && [ "$GCC64_REPO" = "$GCC32_REPO" ]; then
+            if [ -n "${{ inputs.gcc64-repo }}" ] && [ "${{ inputs.gcc64-repo }}" = "${{ inputs.gcc32-repo }}" ]; then
               echo "GCC 64-bit and GCC 32-bit URLs are the same, using gcc path"
-              GCC_REPO=$GCC64_REPO
+              GCC_REPO=${{ inputs.gcc64-repo }}
               git clone --depth=1 $GCC_REPO ${{ env.GCC_PATH }}
             else
-              if [[ "$GCC64_REPO" == *.tar.gz ]]; then
+              if [[ "${{ inputs.gcc64-repo }}" == *.tar.gz ]]; then
                 echo "GCC 64-bit Tarball detected"
                 mkdir -p ${{ env.GCC64_PATH }}
-                curl -RLO $GCC64_REPO
+                curl -RLO ${{ inputs.gcc64-repo }}
                 tar -C ${{ env.GCC64_PATH }}/ -xf *.tar.gz
                 rm -f *.tar.gz
               else
                 echo "GCC 64-bit Repo detected"
-                git clone --depth=1 $GCC64_REPO ${{ env.GCC64_PATH }}
+                git clone --depth=1 ${{ inputs.gcc64-repo }} ${{ env.GCC64_PATH }}
               fi
             fi
-            if [[ "$GCC32_REPO" == *.tar.gz ]]; then
+            if [[ "${{ inputs.gcc32-repo }}" == *.tar.gz ]]; then
               echo "GCC 32-bit Tarball detected"
               mkdir -p ${{ env.GCC32_PATH }}
-              curl -RLO $GCC32_REPO
+              curl -RLO ${{ inputs.gcc32-repo }}
               tar -C ${{ env.GCC32_PATH }}/ -xf *.tar.gz
               rm -f *.tar.gz
             else
               echo "GCC 32-bit Repo detected"
-              git clone --depth=1 $GCC32_REPO ${{ env.GCC32_PATH }}
+              git clone --depth=1 ${{ inputs.gcc32-repo }} ${{ env.GCC32_PATH }}
             fi
           else
             echo "No URLs detected"
@@ -125,12 +120,10 @@ jobs:
           fi
 
       - name: Clone Kernel Source
-        env:
-          KERNEL_REPO: ${{ inputs.kernel-repo }}
         run: |
-          if [ -n "$KERNEL_REPO" ]; then
+          if [ -n "${{ inputs.kernel-repo }}" ]; then
             echo "Kernel Repo detected"
-            git clone --depth=1 $KERNEL_REPO ${{ env.KERNEL_PATH }}
+            git clone --depth=1 ${{ inputs.kernel-repo }} ${{ env.KERNEL_PATH }}
           else
             echo "No Kernel Repo detected"
             exit 1
@@ -138,10 +131,6 @@ jobs:
 
       - name: Install KernelSU (if build type is KernelSU)
         if: ${{ inputs.build-type == 'KERNELSU' }}
-        env: 
-          BUILD_TYPE: ${{ inputs.build-type }}
-          DEFCONFIG: ${{ inputs.defconfig }}
-          KERNELSU_SETUP_SCRIPT: ${{ inputs.ksu-setup-script }}
         run: |
             cd "${{ env.KERNEL_PATH }}"
             if [ -f ".gitmodules" ]; then
@@ -151,22 +140,22 @@ jobs:
               else
                 echo "No KernelSU submodule detected"
               fi
-            elif [ -n "$KERNELSU_SETUP_SCRIPT" ]; then
+            elif [ -n "${{ inputs.ksu-setup-script }}" ]; then
               echo "KernelSU setup script detected"
-              bash -c "$KERNELSU_SETUP_SCRIPT"
+              bash -c "${{ inputs.ksu-setup-script }}"
             else
               echo "No KernelSU submodule or setup script detected, skipping KernelSU build"
             fi
 
       - name: Get Kernel Information
-        env:
-          DEFCONFIG: ${{ inputs.defconfig }}
         run: |
           cd "${{ env.KERNEL_PATH }}"
           {
-            echo "KERNEL_NAME=$(grep -oP 'CONFIG_LOCALVERSION=\K.*' arch/arm64/configs/$DEFCONFIG | tr -d '"' | sed 's/^-//' | tr -d '\r\n' || echo "perf")"
+            echo "KERNEL_NAME=$(grep -oP 'CONFIG_LOCALVERSION=\K.*' arch/arm64/configs/${{ inputs.defconfig }} | tr -d '"' | sed 's/^-//' | tr -d '\r\n' || echo "perf")"
             echo "LINUX_VERSION=$(make kernelversion)"
             echo "LATEST_COMMIT=$(git rev-parse --short HEAD)"
+            echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)"
+            echo "BUILD_TYPE=${{ inputs.build-type }}"
             echo "BUILD_DIFF=$((BUILD_END - BUILD_START))"
           } >> $GITHUB_ENV
 
@@ -176,27 +165,25 @@ jobs:
           make O=out clean
           make O=out mrproper
 
+      - name: Notification if Build Started
+        run: |
+          curl -s -X POST "${{ env.MSG_URL }}" -d message_thread_id="${{ secrets.TELEGRAM_TO }}" -d "parse_mode=Markdown" -d "disable_web_page_view=true" -d "text=🚀 (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build Started! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}```"
+
       - name: Compile the Kernel
-        env:
-          TOOLCHAINS_PATH: ${{ inputs.toolchains-path }}
-          MORE_FLAGS: ${{ inputs.more-flags }}
-          DEFCONFIG: ${{ inputs.defconfig }}
         run: |
           cd "${{ env.KERNEL_PATH }}"
           BUILD_START="$(TZ=Asia/Jakarta date +"%s")"
           export KBUILD_BUILD_USER="${{ env.USER }}"
           export KBUILD_BUILD_HOST="${{ env.HOST }}"
-          export PATH="${{ env.TOOLCHAINS_PATH }}:${PATH}"
+          export PATH="${{ inputs.toolchains-path }}:${PATH}"
 
-          make O=out ARCH=arm64 $DEFCONFIG
-          make O=out -j$(nproc --all) $MORE_FLAGS | tee build.log
+          make O=out ARCH=arm64 ${{ inputs.defconfig }}
+          make O=out -j$(nproc --all) ${{ inputs.more-flags }} 2>&1 | tee build.log
           BUILD_END="$(TZ=Asia/Jakarta date +"%s")"
 
       - name: Zip the Compiled Kernel
-        env:
-          ANYKERNEL3_REPO: ${{ inputs.anykernel3-repo }}
         run: |
-          git clone --depth=1 $ANYKERNEL3_REPO "${{ env.ANYKERNEL_PATH }}"
+          git clone --depth=1 ${{ inputs.anykernel3-repo }} "${{ env.ANYKERNEL_PATH }}"
           rm -rf ${{ env.ANYKERNEL_PATH }}/.git ${{ env.ANYKERNEL_PATH }}/.github ${{ env.ANYKERNEL_PATH }}/LICENSE ${{ env.ANYKERNEL_PATH }}/README.md
 
           for image in Image.gz-dtb Image-dtb Image.gz Image dtbo.img; do
@@ -205,44 +192,29 @@ jobs:
             fi
 
           ZIP_NAME=${{ env.KERNEL_NAME }}-${{ env.LINUX_VERSION }}
-          MD5CHECK=$(md5sum "$ZIP_NAME.zip" | cut -d' ' -f1)
+          MD5_CHECK=$(md5sum "$ZIP_NAME.zip" | cut -d' ' -f1)
           zip -r9 "$ZIP_NAME".zip
-
-      - name: Notification if Build Started
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM_TO }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          format: markdown
-          disable_web_page_preview: true
-          message_file: |
-            🚀 (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build Started! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}```
 
       - name: Notification if Build Success
         if: success()
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM_TO }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          format: markdown
-          disable_web_page_preview: true
-          document: ${{ env.ANYKERNEL_PATH }}/*.zip
-          message_file: |
-            ✅ (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build Successful! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}``` | Build Time: ```${{ env.BUILD_DIFF }}``` | MD5: ```${{ env.MD5CHECK }}```
+          if [ -f "${{ env.ANYKERNEL_PATH }}/$ZIP_NAME.zip" ]; then
+            curl --no-progress-meter -F document=@"${{ env.ANYKERNEL_PATH }}/$ZIP_NAME.zip" "${{ env.DOC_URL }}" -F message_thread_id="${{ secrets.TELEGRAM_TO }}" -F "parse_mode=Markdown" -F "disable_web_page_preview=true" -F "caption= ✅ (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build Successful! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ env.BUILD_TYPE }}``` | Build Time: ```${{ env.BUILD_DIFF }}``` | MD5: ```${{ env.MD5_CHECK }}```
+          else
+            echo "Zip file not found"
+            exit 1
+          fi
 
       - name: Notification if Build Failed
         if: failure() || cancelled()
-        uses: appleboy/telegram-action@master
-        with:
-          to: ${{ secrets.TELEGRAM_TO }}
-          token: ${{ secrets.TELEGRAM_TOKEN }}
-          format: markdown
-          disable_web_page_preview: true
-          document: ${{ env.KERNEL_PATH }}/*.log
-          message_file: |
-            if [ "${{ job.status }}" = "cancelled" ]; then
-              JOB_STATUS="Cancelled"
-            elif [ "${{ job.status }}" = "failure" ]; then
-              JOB_STATUS="Failed"
-            fi
-            ❌ (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build $JOB_STATUS! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}``` | Build Time: ```${{ env.BUILD_DIFF }}```
+        run: |
+          if [ "${{ job.status }}" = "failure" ]; then
+            JOB_STATUS="Failed"
+          elif [ "${{ job.status }}" = "cancelled" ]; then
+            JOB_STATUS="Cancelled"
+          fi
+
+          if [ -n ${{ env.KERNEL_PATH }}/build.log ]; then
+            curl --no-progress-meter -F document=@"${{ env.ANYKERNEL_PATH }}/$ZIP_NAME.zip" "${{ env.DOC_URL }}" -F message_thread_id="${{ secrets.TELEGRAM_TO }}" -F "parse_mode=Markdown" -F "disable_web_page_preview=true" -F "caption= ❌ (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build $JOB_STATUS! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}``` | Build Time: ```${{ env.BUILD_DIFF }}```
+          else
+            curl -s -X POST "${{ env.MSG_URL }}" -d message_thread_id="${{ secrets.TELEGRAM_TO }}" -d "parse_mode=Markdown" -d "disable_web_page_view=true" -d "text= ❌ (https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) Build $JOB_STATUS! | Kernel Name: ```${{ env.KERNEL_NAME }}``` | Linux Version: ```${{ env.LINUX_VERSION }}``` | Latest Commit: ```${{ env.LATEST_COMMIT }}``` | Build Type: ```${{ inputs.build-type }}``` | Build Time: ```${{ env.BUILD_DIFF }}```"
+          fi
