Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -207,6 +207,12 @@ jobs:
           make O=out ARCH=arm64 ${{ inputs.defconfig }}
           make O=out -j$(nproc --all) ${{ inputs.more-flags }} 2>&1 | tee build.log
           BUILD_END="$(TZ=Asia/Jakarta date +"%s")"
+          if [ -f "${{ env.KERNEL_PATH }}/${{ env.KERNEL_BOOT_PATH }}/${{ env.IMAGE }}" ]; then
+            echo "Found Image, build is successful"
+          else
+            echo "Image not found, exiting"
+            exit 1
+          fi
 
       - name: Zip the Compiled Kernel
         id: zip-kernel
@@ -253,7 +259,7 @@ jobs:
 
       - name: Notify to Telegram if Build Successful
         id: notify-if-success
-        if: success() && github.steps.check-kernel.conclusion == 'success' && github.env.BUILD_STATUS == 'true' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: success() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
@@ -271,7 +277,7 @@ jobs:
 
       - name: Send Kernel to Telegram
         id: upload-kernel-and-notify
-        if: success() && github.steps.notify-if-success.conclusion == 'success' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: success() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ env.TELEGRAM_TO }}
@@ -285,7 +291,7 @@ jobs:
 
       - name: Notify to Telegram if Build not Successful
         id: notify-if-not-success
-        if: failure() && github.steps.check-kernel.conclusion == 'success' && github.env.BUILD_STATUS == 'false' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: failure() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
@@ -303,7 +309,7 @@ jobs:
 
       - name: Send Error log to Telegram
         id: upload-log-and-notify
-        if: failure() && github.steps.notify-if-not-success.conclusion == 'success' && github.env.LOG_STATUS == 'true' && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
+        if: failure() && github.secrets.TELEGRAM_TO != '' && github.secrets.TELEGRAM_TOKEN != ''
         uses: appleboy/telegram-action@master
         with:
           to: ${{ env.TELEGRAM_TO }}
